// Dev-only: writes tests/fixtures/data.gen.ts, the captured SSE fixtures and example.styx.json as string
// constants, byte for byte, because `claude plugin test` gives test files no filesystem. With --check it
// writes nothing, and exits 1 when the committed file differs from what it would write.
//
//   bun scripts/gen-test-data.ts [--check]
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(import.meta.dir, '..')
const SSE_DIR = join(ROOT, 'tests', 'fixtures', 'sse')
const OUT = join(ROOT, 'tests', 'fixtures', 'data.gen.ts')
const sse = Object.fromEntries(
  readdirSync(SSE_DIR)
    .filter(f => f.endsWith('.sse'))
    .sort()
    .map(f => [f, readFileSync(join(SSE_DIR, f), 'utf8')]),
)
const example = readFileSync(join(ROOT, 'example.styx.json'), 'utf8')
const text =
  '// Generated by scripts/gen-test-data.ts from tests/fixtures/sse/*.sse and example.styx.json; do not edit.\n' +
  `export const SSE: Readonly<Record<string, string>> = ${JSON.stringify(sse, null, 2)}\n\n` +
  `export const EXAMPLE_CONFIG = ${JSON.stringify(example)}\n`
const summary = `${Object.keys(sse).length} SSE fixtures, example.styx.json (${example.length} chars)`

if (process.argv.includes('--check')) {
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== text) {
    console.error('tests/fixtures/data.gen.ts is stale: run bun scripts/gen-test-data.ts')
    process.exit(1)
  }
  console.log(`data.gen.ts: up to date (${summary})`)
} else {
  writeFileSync(OUT, text)
  console.log(`data.gen.ts: ${summary}`)
}
